theme = "modern"
icons = "material"

[[block]]
block = "music"
player = "mpd"
buttons = ["play", "next"]

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
service = { name = "openweathermap", api_key = "927ab4f14847ad46d123ce3efab06bb1", city_id = "1275971", units = "metric" }

[[block]]
block = "time"
interval = 1
format = "[%a %d/%m] [%I:%m:%S %p]"

[[block]]
block = "networkmanager"
on_click = "termite -e nmtui"

[[block]]
block = "backlight"
device = "intel_backlight"
step_width = 5

[[block]]
block = "sound"
step_width = 3


[[block]]
block = "battery"
interval = 1
warning = 15
critical = 10
format = "{percentage}% {time}"
